### PR TITLE
remove ordering of CONES

### PR DESCRIPTION
**Pull request by akshay326**
still some scaling left :D

### CODE REVIEW

**Comment by matbesancon** [comment]
should this be merged?

**Comment by matbesancon** [comment]
it seems to be blocking other PRs in DiffOpt

**Comment by akshay326** [comment]
we can go w/o this too, but if the matrices follow constraints in the natural order they are added to an optimizer, then we can very easily differentiate a specific constraint / parameter

**Review by blegat — APPROVED** [review]

**Review by matbesancon — APPROVED** [review]

**Comment by akshay326** [comment]
is there something missing in this PR? Since its not merged, I've to explain people how to make https://github.com/jump-dev/DiffOpt.jl/pull/43 work 😅

**Pull request merged**
